#undef TAPPING_TERM
#define TAPPING_TERM 1000

#define PERMISSIVE_HOLD

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 120000

#undef RGB_MATRIX_VAL_STEP
#define RGB_MATRIX_VAL_STEP 20

#define USB_SUSPEND_WAKEUP_DELAY 0
#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "DwxJJ/NoJee4"
#define LAYER_STATE_16BIT

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

